
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
    - "**/l10n/**"
  errors:
    missing_required_param: error
    missing_return: error
    invalid_assignment: error
    dead_code: error

linter:
  rules:
    avoid_unnecessary_containers: true
    cancel_subscriptions: true
    close_sinks: true
    unnecessary_statements: true
    
    always_declare_return_types: true
    avoid_print: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    deprecated_consistency: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    omit_local_variable_types: true
    prefer_adjacent_string_concatenation: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    use_late_for_private_fields_and_variables: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true
    void_checks: true
    always_use_package_imports: true

