// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:travel_planner/features/auth/data/models/user_model.dart';
import 'package:travel_planner/features/trips/data/models/trip_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(TripModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(TripModelAdapter());
    registerAdapter(UserModelAdapter());
  }
}
